USE [21127699_ETL_Assigment]
go

CREATE TABLE DATA_FLOW(
ID INT NOT NULL IDENTITY(1,1),
Name VARCHAR(20) NOT NULL,
LSET DATETIME,
CET DATETIME,
CONSTRAINT PK_Data_Flow PRIMARY KEY CLUSTERED (ID)
)
go

CREATE TRIGGER insert_dataflow on DATA_FLOW AFTER INSERT AS
BEGIN
	UPDATE DATA_FLOW
	SET LSET = GETDATE(), CET = GETDATE()
	WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
go

-- insert du lieu
INSERT INTO DATA_FLOW (Name, LSET, CET) VALUES ('HocSinh', null, null);
INSERT INTO DATA_FLOW (Name, LSET, CET) VALUES ('LopHoc', null, null);


SELECT * FROM LopHoc_Stage;
SELECT * FROM HocSinh_Stage;

insert LopHoc_Stage values ('M8', 'Lớp một 8', GETDATE(), GETDATE())
